### ISSUE TITLE
Universal React: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ckuijjer** [cmswalker/fullpage-react#9]
I'm trying to use your awesome library in a universal react environment, where the initial render is done server side.

NodeJS isn't able to import the library as it's dependent on the `window` object existing, which doesn't exist in a server side environment.

```
/Users/ckuijjer/src/exact-connect/web/node_modules/fullpage-react/dist/utils/renderUtils.js:15
	var isOpera = !!window.opr && !!opr.addons || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;
	                ^

ReferenceError: window is not defined
    at Object.browser (/Users/ckuijjer/src/exact-connect/web/node_modules/fullpage-react/dist/utils/renderUtils.js:15:18)
    at Object.<anonymous> (/Users/ckuijjer/src/exact-connect/web/node_modules/fullpage-react/dist/components/fullpage.js:19:27)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ckuijjer/src/exact-connect/web/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

```

If the BROWSER, ELEMENT_BROWSERS and BODY variables are initialized on the first use, this isn't an issue anymore.

I've created pull request #10 to solve this.

**Comment by cmswalker** [comment]
Thanks for this, closed via https://github.com/cmswalker/fullpage-react/pull/10

**Comment by ckuijjer** [comment]
Awesome! Thanks a lot
